#!/usr/bin/env bash
# Clean stale Vite / TypeScript caches and re-run the typecheck.
# Use this when TS errors persist after a fix or after large refactors.
set -euo pipefail

cd "$(dirname "$0")/.."

echo "→ Removing build & TS caches"
rm -rf \
  node_modules/.vite \
  node_modules/.cache \
  node_modules/.tmp \
  .tanstack \
  .vite \
  dist \
  .tsbuildinfo \
  tsconfig.tsbuildinfo

# Auto-generated by the TanStack Router plugin — safe to drop, will regenerate
rm -f src/routeTree.gen.ts

echo "→ Running TypeScript in --noEmit mode"
npx tsc --noEmit --pretty

echo "✓ Typecheck complete"
