/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as KakisIndexRouteImport } from './routes/kakis.index'
import { Route as BidsIndexRouteImport } from './routes/bids.index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as ProfileSetupRouteImport } from './routes/profile.setup'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const KakisIndexRoute = KakisIndexRouteImport.update({
  id: '/kakis/',
  path: '/kakis/',
  getParentRoute: () => rootRouteImport,
} as any)
const BidsIndexRoute = BidsIndexRouteImport.update({
  id: '/bids/',
  path: '/bids/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile/setup',
  path: '/profile/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/setup': typeof ProfileSetupRoute
  '/auth/': typeof AuthIndexRoute
  '/bids/': typeof BidsIndexRoute
  '/kakis/': typeof KakisIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/setup': typeof ProfileSetupRoute
  '/auth': typeof AuthIndexRoute
  '/bids': typeof BidsIndexRoute
  '/kakis': typeof KakisIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/setup': typeof ProfileSetupRoute
  '/auth/': typeof AuthIndexRoute
  '/bids/': typeof BidsIndexRoute
  '/kakis/': typeof KakisIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/auth/login'
    | '/auth/signup'
    | '/profile/edit'
    | '/profile/setup'
    | '/auth/'
    | '/bids/'
    | '/kakis/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/auth/login'
    | '/auth/signup'
    | '/profile/edit'
    | '/profile/setup'
    | '/auth'
    | '/bids'
    | '/kakis'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/auth/login'
    | '/auth/signup'
    | '/profile/edit'
    | '/profile/setup'
    | '/auth/'
    | '/bids/'
    | '/kakis/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  AuthIndexRoute: typeof AuthIndexRoute
  BidsIndexRoute: typeof BidsIndexRoute
  KakisIndexRoute: typeof KakisIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kakis/': {
      id: '/kakis/'
      path: '/kakis'
      fullPath: '/kakis/'
      preLoaderRoute: typeof KakisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bids/': {
      id: '/bids/'
      path: '/bids'
      fullPath: '/bids/'
      preLoaderRoute: typeof BidsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/setup': {
      id: '/profile/setup'
      path: '/profile/setup'
      fullPath: '/profile/setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  AuthIndexRoute: AuthIndexRoute,
  BidsIndexRoute: BidsIndexRoute,
  KakisIndexRoute: KakisIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
